image: alpine:latest

pages:
  stage: build
  script:
    - apk add nodejs npm python3 py3-pip
    - python3 -m venv venv
    - . venv
    - pip install --no-cache-dir -r dependencies.txt
    - npm ci
    - npm build
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
